import { describe, expect, it } from "vitest";

import { TASK_REST_ROUTES } from "../src/index.ts";

describe("TASK_REST_ROUTES", () => {
  it("snapshots active, explicit-project and activity task routes", () => {
    expect(TASK_REST_ROUTES.map(({ id, method, path, group, responseMode, scope }) => ({
      id,
      method,
      path,
      group,
      responseMode,
      scope,
    }))).toMatchInlineSnapshot(`
      [
        {
          "group": "task",
          "id": "tasks.list.active",
          "method": "GET",
          "path": "/api/tasks",
          "responseMode": "json",
          "scope": "active-project",
        },
        {
          "group": "task",
          "id": "tasks.create.active",
          "method": "POST",
          "path": "/api/tasks",
          "responseMode": "json",
          "scope": "active-project",
        },
        {
          "group": "task",
          "id": "tasks.detail.active",
          "method": "GET",
          "path": "/api/tasks/:id",
          "responseMode": "json",
          "scope": "active-project",
        },
        {
          "group": "task",
          "id": "tasks.delete.active",
          "method": "DELETE",
          "path": "/api/tasks/:id",
          "responseMode": "json",
          "scope": "active-project",
        },
        {
          "group": "task",
          "id": "tasks.transition.active",
          "method": "POST",
          "path": "/api/tasks/:id/transition",
          "responseMode": "json",
          "scope": "active-project",
        },
        {
          "group": "task",
          "id": "tasks.dispatch.active",
          "method": "POST",
          "path": "/api/tasks/:id/dispatch",
          "responseMode": "json",
          "scope": "active-project",
        },
        {
          "group": "task",
          "id": "tasks.retryFromWorker.active",
          "method": "POST",
          "path": "/api/tasks/:id/retry-from-worker",
          "responseMode": "json",
          "scope": "active-project",
        },
        {
          "group": "run",
          "id": "tasks.runAgent.active",
          "method": "POST",
          "path": "/api/tasks/:id/run-agent",
          "responseMode": "json",
          "scope": "active-project",
        },
        {
          "group": "run",
          "id": "tasks.cancelRun.active",
          "method": "POST",
          "path": "/api/tasks/:id/cancel-run",
          "responseMode": "json",
          "scope": "active-project",
        },
        {
          "group": "task",
          "id": "tasks.addComment.active",
          "method": "POST",
          "path": "/api/tasks/:id/comments",
          "responseMode": "json",
          "scope": "active-project",
        },
        {
          "group": "task",
          "id": "tasks.cost.active",
          "method": "GET",
          "path": "/api/tasks/:id/cost",
          "responseMode": "json",
          "scope": "active-project",
        },
        {
          "group": "task",
          "id": "tasks.addFilePath.active",
          "method": "POST",
          "path": "/api/tasks/:id/file-paths",
          "responseMode": "json",
          "scope": "active-project",
        },
        {
          "group": "task",
          "id": "tasks.deleteFilePath.active",
          "method": "DELETE",
          "path": "/api/tasks/:id/file-paths/:fpId",
          "responseMode": "json",
          "scope": "active-project",
        },
        {
          "group": "board",
          "id": "board.cost.active",
          "method": "GET",
          "path": "/api/board/cost",
          "responseMode": "json",
          "scope": "active-project",
        },
        {
          "group": "task",
          "id": "tasks.list.project",
          "method": "GET",
          "path": "/api/projects/:code/tasks",
          "responseMode": "json",
          "scope": "explicit-project",
        },
        {
          "group": "task",
          "id": "tasks.create.project",
          "method": "POST",
          "path": "/api/projects/:code/tasks",
          "responseMode": "json",
          "scope": "explicit-project",
        },
        {
          "group": "task",
          "id": "tasks.detail.project",
          "method": "GET",
          "path": "/api/projects/:code/tasks/:id",
          "responseMode": "json",
          "scope": "explicit-project",
        },
        {
          "group": "task",
          "id": "tasks.delete.project",
          "method": "DELETE",
          "path": "/api/projects/:code/tasks/:id",
          "responseMode": "json",
          "scope": "explicit-project",
        },
        {
          "group": "task",
          "id": "tasks.transition.project",
          "method": "POST",
          "path": "/api/projects/:code/tasks/:id/transition",
          "responseMode": "json",
          "scope": "explicit-project",
        },
        {
          "group": "task",
          "id": "tasks.dispatch.project",
          "method": "POST",
          "path": "/api/projects/:code/tasks/:id/dispatch",
          "responseMode": "json",
          "scope": "explicit-project",
        },
        {
          "group": "task",
          "id": "tasks.retryFromWorker.project",
          "method": "POST",
          "path": "/api/projects/:code/tasks/:id/retry-from-worker",
          "responseMode": "json",
          "scope": "explicit-project",
        },
        {
          "group": "run",
          "id": "tasks.runAgent.project",
          "method": "POST",
          "path": "/api/projects/:code/tasks/:id/run-agent",
          "responseMode": "json",
          "scope": "explicit-project",
        },
        {
          "group": "run",
          "id": "tasks.cancelRun.project",
          "method": "POST",
          "path": "/api/projects/:code/tasks/:id/cancel-run",
          "responseMode": "json",
          "scope": "explicit-project",
        },
        {
          "group": "task",
          "id": "tasks.addComment.project",
          "method": "POST",
          "path": "/api/projects/:code/tasks/:id/comments",
          "responseMode": "json",
          "scope": "explicit-project",
        },
        {
          "group": "task",
          "id": "tasks.cost.project",
          "method": "GET",
          "path": "/api/projects/:code/tasks/:id/cost",
          "responseMode": "json",
          "scope": "explicit-project",
        },
        {
          "group": "task",
          "id": "tasks.addFilePath.project",
          "method": "POST",
          "path": "/api/projects/:code/tasks/:id/file-paths",
          "responseMode": "json",
          "scope": "explicit-project",
        },
        {
          "group": "task",
          "id": "tasks.deleteFilePath.project",
          "method": "DELETE",
          "path": "/api/projects/:code/tasks/:id/file-paths/:fpId",
          "responseMode": "json",
          "scope": "explicit-project",
        },
        {
          "group": "board",
          "id": "board.cost.project",
          "method": "GET",
          "path": "/api/projects/:code/board/cost",
          "responseMode": "json",
          "scope": "explicit-project",
        },
        {
          "group": "activity",
          "id": "runs.events",
          "method": "GET",
          "path": "/api/runs/:id/events",
          "responseMode": "sse",
          "scope": "run-activity",
        },
        {
          "group": "activity",
          "id": "runs.activity",
          "method": "GET",
          "path": "/api/runs/:id/activity",
          "responseMode": "json",
          "scope": "run-activity",
        },
        {
          "group": "activity",
          "id": "tasks.activity",
          "method": "GET",
          "path": "/api/tasks/:id/activity",
          "responseMode": "json",
          "scope": "run-activity",
        },
      ]
    `);
  });

  it("keeps active and explicit project task routes paired", () => {
    const active = TASK_REST_ROUTES.filter((route) => route.scope === "active-project");
    const explicit = TASK_REST_ROUTES.filter((route) => route.scope === "explicit-project");

    expect(explicit.map((route) => route.id)).toEqual(
      active.map((route) => route.id.replace(".active", ".project")),
    );
  });
});
