import type { RestRouteContract } from "./rest-projects.ts";

export const PROJECT_MUTATION_REST_ROUTES: readonly RestRouteContract[] = [
  {
    id: "projects.create",
    method: "POST",
    path: "/api/projects",
    group: "project",
    auth: "bearer",
    responseMode: "json",
    description: "Create a project database and enqueue its initial skill scan.",
  },
  {
    id: "projects.selectActive",
    method: "PATCH",
    path: "/api/projects/active",
    group: "project",
    auth: "bearer",
    responseMode: "json",
    description: "Select the active project and enqueue a switch scan when needed.",
  },
  {
    id: "projects.update",
    method: "PATCH",
    path: "/api/projects/:code",
    group: "project",
    auth: "bearer",
    responseMode: "json",
    description: "Patch mutable project fields with optimistic version checks.",
  },
  {
    id: "projects.delete",
    method: "DELETE",
    path: "/api/projects/:code",
    group: "project",
    auth: "bearer",
    responseMode: "json",
    description: "Move a project database to trash and clear active selection if needed.",
  },
] as const;

export const SKILL_REST_ROUTES: readonly RestRouteContract[] = [
  {
    id: "skills.list",
    method: "GET",
    path: "/api/skills",
    group: "skill",
    auth: "bearer",
    responseMode: "json",
    description: "List indexed project skills plus built-in skills.",
  },
  {
    id: "skills.dirs",
    method: "GET",
    path: "/api/skills/dirs",
    group: "skill",
    auth: "bearer",
    responseMode: "json",
    description: "List skill directory filters for the active project.",
  },
  {
    id: "skills.scanLatest",
    method: "GET",
    path: "/api/skills/scan/latest",
    group: "skill",
    auth: "bearer",
    responseMode: "json",
    description: "Read the latest skill scan row for the active project.",
  },
  {
    id: "skills.scanEvents",
    method: "GET",
    path: "/api/skills/scan/events",
    group: "skill",
    auth: "bearer",
    responseMode: "sse",
    description: "Stream skill scan lifecycle events for the active project.",
  },
  {
    id: "skills.scan",
    method: "POST",
    path: "/api/skills/scan",
    group: "skill",
    auth: "bearer",
    responseMode: "json",
    description: "Queue a skill scan for the active project.",
  },
  {
    id: "skills.detail",
    method: "GET",
    path: "/api/skills/:id",
    group: "skill",
    auth: "bearer",
    responseMode: "json",
    description: "Read a built-in or indexed project skill with body content.",
  },
  {
    id: "skills.update",
    method: "PUT",
    path: "/api/skills/:id",
    group: "skill",
    auth: "bearer",
    responseMode: "json",
    description: "Update an indexed project SKILL.md file and its index metadata.",
  },
] as const;

export const SESSION_REST_ROUTES: readonly RestRouteContract[] = [
  {
    id: "sessions.list",
    method: "GET",
    path: "/api/sessions",
    group: "session",
    auth: "bearer",
    responseMode: "json",
    description: "List recorded CLI and Agentboard sessions from session databases.",
  },
  {
    id: "sessions.events",
    method: "GET",
    path: "/api/sessions/:hash/events/:sessionId",
    group: "session",
    auth: "bearer",
    responseMode: "json",
    description: "Read events and enrichment for one recorded session.",
  },
] as const;

export const SUPPORT_REST_ROUTES: readonly RestRouteContract[] = [
  {
    id: "healthz",
    method: "GET",
    path: "/healthz",
    group: "health",
    auth: "bearer",
    responseMode: "json",
    description: "Read authenticated server health and observability snapshot.",
  },
  {
    id: "prompts.detail",
    method: "GET",
    path: "/api/prompts/:kind/:id",
    group: "prompt",
    auth: "bearer",
    responseMode: "json",
    description: "Read raw prompt markdown for a role or skill prompt id.",
  },
  {
    id: "costs.runs",
    method: "GET",
    path: "/api/projects/:code/costs",
    group: "cost",
    auth: "bearer",
    responseMode: "json",
    description: "Read recent run cost rows for a project.",
  },
  {
    id: "costs.total",
    method: "GET",
    path: "/api/projects/:code/costs/total",
    group: "cost",
    auth: "bearer",
    responseMode: "json",
    description: "Read all-time, seven-day and thirty-day project cost totals.",
  },
  {
    id: "logs.run",
    method: "GET",
    path: "/api/logs/:runId",
    group: "log",
    auth: "bearer",
    responseMode: "ndjson",
    description: "Stream a run log JSONL file.",
  },
] as const;

export const LEGACY_REST_ROUTES: readonly RestRouteContract[] = [
  ...PROJECT_MUTATION_REST_ROUTES,
  ...SKILL_REST_ROUTES,
  ...SESSION_REST_ROUTES,
  ...SUPPORT_REST_ROUTES,
] as const;
